import type { Product } from './types';

export const products: Product[] = [
  // === VICTORY COLLECTION ($500–$2,000) ===
  {
    id: 'court-royale-pendant',
    productCode: 'GUP0002',
    name: 'Court Royale',
    price: 980,
    priceDisplay: '$980',
    collection: 'victory',
    category: 'pendant',
    description: 'A miniature pickleball rendered in polished 14K gold — every hole precision-cut, every curve hand-finished. The Court Royale captures the soul of the game in a single, wearable sphere. Suspended from a delicate cable chain, it catches the light the way a rally catches your breath.',
    tagline: 'The game, distilled.',
    badges: [],
    occasions: ['self-gift', 'gift', 'birthday', 'tournament-win'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/court-royale-hero_white.jpg',
    complementaryIds: ['rally-drops-earrings', 'ace-studs-earrings', 'first-win-ring'],
    gallery: [
      { src: '/images/court-royale-hero_white.jpg', alt: 'Court Royale pendant — front view on white background', label: 'Front View' },
      { src: '/images/court-royale-hero_gradient.jpg', alt: 'Court Royale pendant — gradient background', label: 'Gradient' },
      { src: '/images/court-royale-lifestyle_marble.jpg', alt: 'Court Royale pendant — on marble with rose petal', label: 'Lifestyle' },
      { src: '/images/court-royale-lifestyle_velvet.jpg', alt: 'Court Royale pendant — dramatic shot on dark velvet', label: 'Velvet' },
      { src: '/images/court-royale-detail_macro.jpg', alt: 'Court Royale pendant — macro detail of gold surface', label: 'Detail' },
      { src: '/images/court-royale-banner_hero.jpg', alt: 'Court Royale pendant — banner view', label: 'Banner' },
    ],
    specs: {
      metalType: '14K Yellow Gold',
      weight: '3.2g',
      dimensions: '12mm sphere',
      chain: '18" cable chain with lobster clasp',
    },
  },
  {
    id: 'rally-drops-earrings',
    productCode: 'GUE0001',
    name: 'Rally Drops',
    price: 720,
    priceDisplay: '$720',
    collection: 'victory',
    category: 'earrings',
    description: 'Lever-back drop earrings shaped like miniature pickleballs, swinging with every step you take off the court. Each sphere is hand-perforated and polished to a mirror finish — catching light from every angle, turning heads at every gathering.',
    tagline: 'Movement meets brilliance.',
    badges: [],
    occasions: ['self-gift', 'gift', 'birthday', 'everyday'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/rally-drops-hero_white.jpg',
    complementaryIds: ['court-royale-pendant', 'ace-studs-earrings', 'rally-bracelet'],
    gallery: [
      { src: '/images/rally-drops-hero_white.jpg', alt: 'Rally Drops earrings — front view on white background', label: 'Front View' },
      { src: '/images/rally-drops-hero_gradient.jpg', alt: 'Rally Drops earrings — warm gradient background', label: 'Gradient' },
      { src: '/images/rally-drops-on_model.jpg', alt: 'Rally Drops earrings — worn on model', label: 'On Model' },
      { src: '/images/rally-drops-lifestyle_marble.jpg', alt: 'Rally Drops earrings — on marble surface', label: 'Lifestyle' },
      { src: '/images/rally-drops-lifestyle_velvet.jpg', alt: 'Rally Drops earrings — on dark velvet', label: 'Velvet' },
      { src: '/images/rally-drops-sport_context.jpg', alt: 'Rally Drops earrings — with pickleball equipment', label: 'On Court' },
      { src: '/images/rally-drops-detail_macro.jpg', alt: 'Rally Drops earrings — macro detail of gold surface', label: 'Detail' },
    ],
    specs: {
      metalType: '14K Yellow Gold',
      weight: '4.8g (pair)',
      dimensions: '12mm sphere, 28mm total drop',
      chain: 'Lever-back closure',
    },
  },
  {
    id: 'ace-studs-earrings',
    productCode: 'GUE0002',
    name: 'Ace Studs',
    price: 580,
    priceDisplay: '$580',
    collection: 'victory',
    category: 'earrings',
    description: 'Half-sphere pickleball studs that sit flush against the ear — bold enough to notice, subtle enough for every day. The push-back posts are engineered for comfort, so you can wear them from the morning match to the evening out.',
    tagline: 'Quiet confidence.',
    badges: [],
    occasions: ['self-gift', 'gift', 'birthday', 'everyday'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/ace-studs-hero_gradient.jpg',
    complementaryIds: ['court-royale-pendant', 'rally-drops-earrings', 'rally-bracelet'],
    gallery: [
      { src: '/images/ace-studs-hero_gradient.jpg', alt: 'Ace Studs earrings — gradient background showing front and side', label: 'Front View' },
      { src: '/images/ace-studs-on_model.jpg', alt: 'Ace Studs earrings — worn on model', label: 'On Model' },
      { src: '/images/ace-studs-lifestyle_marble.jpg', alt: 'Ace Studs earrings — on marble surface', label: 'Lifestyle' },
      { src: '/images/ace-studs-lifestyle_velvet.jpg', alt: 'Ace Studs earrings — on dark velvet', label: 'Velvet' },
      { src: '/images/ace-studs-sport_context.jpg', alt: 'Ace Studs earrings — with pickleball equipment', label: 'On Court' },
      { src: '/images/ace-studs-detail_macro.jpg', alt: 'Ace Studs earrings — macro detail of gold surface', label: 'Detail' },
      { src: '/images/ace-studs-banner_hero.jpg', alt: 'Ace Studs earrings — banner view', label: 'Banner' },
    ],
    specs: {
      metalType: '14K Yellow Gold',
      weight: '3.6g (pair)',
      dimensions: '10mm half-sphere',
      chain: 'Push-back butterfly closure',
    },
  },
  {
    id: 'sparkle-studs-gold',
    productCode: 'GUE0003',
    name: 'Sparkle Studs Gold',
    price: 850,
    priceDisplay: '$850',
    collection: 'victory',
    category: 'earrings',
    description: 'Diamond-set pickleball studs in warm 14K yellow gold. Each bezel-set stone catches light from every angle — a quiet statement that speaks volumes about your taste and your game.',
    tagline: 'Brilliance, refined.',
    badges: ['Diamond Set'],
    occasions: ['self-gift', 'gift', 'birthday', 'anniversary'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/sparkle-studs-gold-hero_white.jpg',
    complementaryIds: ['court-royale-pendant', 'sparkle-drops-gold'],
    gallery: [
      { src: '/images/sparkle-studs-gold-hero_white.jpg', alt: 'Sparkle Studs Gold — front view', label: 'Front View' },
      { src: '/images/sparkle-studs-gold-hero_gradient.jpg', alt: 'Sparkle Studs Gold — gradient', label: 'Gradient' },
      { src: '/images/sparkle-studs-gold-on_model.jpg', alt: 'Sparkle Studs Gold — on model', label: 'On Model' },
      { src: '/images/sparkle-studs-gold-lifestyle_marble.jpg', alt: 'Sparkle Studs Gold — lifestyle', label: 'Lifestyle' },
      { src: '/images/sparkle-studs-gold-lifestyle_velvet.jpg', alt: 'Sparkle Studs Gold — velvet', label: 'Velvet' },
      { src: '/images/sparkle-studs-gold-sport_context.jpg', alt: 'Sparkle Studs Gold — on court', label: 'On Court' },
      { src: '/images/sparkle-studs-gold-detail_macro.jpg', alt: 'Sparkle Studs Gold — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K Yellow Gold', weight: '4.2g (pair)', dimensions: '10mm half-sphere', chain: 'Push-back butterfly closure' },
  },
  {
    id: 'sparkle-studs-silver',
    productCode: 'GUE0003-VZ',
    name: 'Sparkle Studs Silver',
    price: 920,
    priceDisplay: '$920',
    collection: 'victory',
    category: 'earrings',
    description: 'The white gold edition of our diamond-set pickleball studs — cooler in tone, equally brilliant. Rhodium-plated for lasting polish, these studs pair effortlessly with everything from courtside whites to evening black.',
    tagline: 'Cool brilliance.',
    badges: ['Diamond Set'],
    occasions: ['self-gift', 'gift', 'birthday', 'anniversary'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/sparkle-studs-silver-hero_white.jpg',
    complementaryIds: ['sparkle-studs-gold', 'sparkle-drops-silver'],
    gallery: [
      { src: '/images/sparkle-studs-silver-hero_white.jpg', alt: 'Sparkle Studs Silver — front view', label: 'Front View' },
      { src: '/images/sparkle-studs-silver-hero_gradient.jpg', alt: 'Sparkle Studs Silver — gradient', label: 'Gradient' },
      { src: '/images/sparkle-studs-silver-on_model.jpg', alt: 'Sparkle Studs Silver — on model', label: 'On Model' },
      { src: '/images/sparkle-studs-silver-lifestyle_marble.jpg', alt: 'Sparkle Studs Silver — lifestyle', label: 'Lifestyle' },
      { src: '/images/sparkle-studs-silver-lifestyle_velvet.jpg', alt: 'Sparkle Studs Silver — velvet', label: 'Velvet' },
      { src: '/images/sparkle-studs-silver-sport_context.jpg', alt: 'Sparkle Studs Silver — on court', label: 'On Court' },
      { src: '/images/sparkle-studs-silver-detail_macro.jpg', alt: 'Sparkle Studs Silver — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K White Gold', weight: '4.2g (pair)', dimensions: '10mm half-sphere', chain: 'Push-back butterfly closure' },
  },
  {
    id: 'sparkle-drops-gold',
    productCode: 'GUE0004',
    name: 'Sparkle Drops Gold',
    price: 1100,
    priceDisplay: '$1,100',
    collection: 'victory',
    category: 'earrings',
    description: 'Diamond-studded lever-back drop earrings in 14K yellow gold. The full pickleball sphere swings with every movement — a dazzling display of craftsmanship that turns heads on and off the court.',
    tagline: 'Swing with brilliance.',
    badges: ['Diamond Set'],
    occasions: ['self-gift', 'gift', 'anniversary', 'milestone'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/sparkle-drops-gold-hero_white.jpg',
    complementaryIds: ['sparkle-studs-gold', 'court-royale-pendant'],
    gallery: [
      { src: '/images/sparkle-drops-gold-hero_white.jpg', alt: 'Sparkle Drops Gold — front view', label: 'Front View' },
      { src: '/images/sparkle-drops-gold-hero_gradient.jpg', alt: 'Sparkle Drops Gold — gradient', label: 'Gradient' },
      { src: '/images/sparkle-drops-gold-on_model.jpg', alt: 'Sparkle Drops Gold — on model', label: 'On Model' },
      { src: '/images/sparkle-drops-gold-lifestyle_marble.jpg', alt: 'Sparkle Drops Gold — lifestyle', label: 'Lifestyle' },
      { src: '/images/sparkle-drops-gold-lifestyle_velvet.jpg', alt: 'Sparkle Drops Gold — velvet', label: 'Velvet' },
      { src: '/images/sparkle-drops-gold-sport_context.jpg', alt: 'Sparkle Drops Gold — on court', label: 'On Court' },
      { src: '/images/sparkle-drops-gold-detail_macro.jpg', alt: 'Sparkle Drops Gold — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K Yellow Gold', weight: '5.6g (pair)', dimensions: '12mm sphere, 30mm total drop', chain: 'Lever-back closure' },
  },
  {
    id: 'sparkle-drops-silver',
    productCode: 'GUE0004-VZ',
    name: 'Sparkle Drops Silver',
    price: 1180,
    priceDisplay: '$1,180',
    collection: 'victory',
    category: 'earrings',
    description: 'White gold lever-back drops with diamond-set spheres. The cool rhodium finish gives these drops an icy elegance — perfect for the player who prefers silver to gold but refuses to compromise on sparkle.',
    tagline: 'Ice and fire.',
    badges: ['Diamond Set'],
    occasions: ['self-gift', 'gift', 'anniversary', 'milestone'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/sparkle-drops-silver-hero_gradient.jpg',
    complementaryIds: ['sparkle-studs-silver', 'paddle-pave-silver'],
    gallery: [
      { src: '/images/sparkle-drops-silver-hero_gradient.jpg', alt: 'Sparkle Drops Silver — gradient view', label: 'Front View' },
      { src: '/images/sparkle-drops-silver-hero_white.jpg', alt: 'Sparkle Drops Silver — white background', label: 'White' },
      { src: '/images/sparkle-drops-silver-on_model.jpg', alt: 'Sparkle Drops Silver — on model', label: 'On Model' },
      { src: '/images/sparkle-drops-silver-lifestyle_marble.jpg', alt: 'Sparkle Drops Silver — lifestyle', label: 'Lifestyle' },
      { src: '/images/sparkle-drops-silver-lifestyle_velvet.jpg', alt: 'Sparkle Drops Silver — velvet', label: 'Velvet' },
      { src: '/images/sparkle-drops-silver-sport_context.jpg', alt: 'Sparkle Drops Silver — on court', label: 'On Court' },
      { src: '/images/sparkle-drops-silver-detail_macro.jpg', alt: 'Sparkle Drops Silver — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K White Gold', weight: '5.6g (pair)', dimensions: '12mm sphere, 30mm total drop', chain: 'Lever-back closure' },
  },
  {
    id: 'diamond-ball-pendant',
    productCode: 'GUP0003',
    name: 'Diamond Court Pendant',
    price: 1250,
    priceDisplay: '$1,250',
    collection: 'victory',
    category: 'pendant',
    description: 'The Court Royale, elevated with diamonds. Every perforation on this pickleball sphere is set with a brilliant-cut stone — transforming a beloved silhouette into something truly extraordinary.',
    tagline: 'Every angle shines.',
    badges: ['Diamond Set'],
    occasions: ['self-gift', 'gift', 'milestone', 'anniversary'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/diamond-ball-pendant-hero_white.jpg',
    complementaryIds: ['sparkle-studs-gold', 'sparkle-drops-gold'],
    gallery: [
      { src: '/images/diamond-ball-pendant-hero_white.jpg', alt: 'Diamond Court Pendant — front view', label: 'Front View' },
      { src: '/images/diamond-ball-pendant-hero_gradient.jpg', alt: 'Diamond Court Pendant — gradient', label: 'Gradient' },
      { src: '/images/diamond-ball-pendant-on_model.jpg', alt: 'Diamond Court Pendant — on model', label: 'On Model' },
      { src: '/images/diamond-ball-pendant-lifestyle_marble.jpg', alt: 'Diamond Court Pendant — lifestyle', label: 'Lifestyle' },
      { src: '/images/diamond-ball-pendant-lifestyle_velvet.jpg', alt: 'Diamond Court Pendant — velvet', label: 'Velvet' },
      { src: '/images/diamond-ball-pendant-sport_context.jpg', alt: 'Diamond Court Pendant — on court', label: 'On Court' },
      { src: '/images/diamond-ball-pendant-detail_macro.jpg', alt: 'Diamond Court Pendant — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K Yellow Gold', weight: '4.1g', dimensions: '12mm sphere', chain: '18" cable chain with lobster clasp' },
  },
  {
    id: 'paddle-pave-gold',
    productCode: 'GUP0006',
    name: 'Paddle Pav\u00e9 Gold',
    price: 1450,
    priceDisplay: '$1,450',
    collection: 'victory',
    category: 'pendant',
    description: 'A full pickleball paddle rendered in 14K gold and blanketed in pav\u00e9 diamonds. The handle is rope-textured for authenticity. This is the piece that makes strangers ask about your necklace — and your game.',
    tagline: 'The paddle, immortalized.',
    badges: ['Pav\u00e9 Diamond'],
    occasions: ['self-gift', 'gift', 'milestone', 'tournament-win'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/paddle-pave-gold-hero_white.jpg',
    complementaryIds: ['sparkle-studs-gold', 'court-royale-pendant'],
    gallery: [
      { src: '/images/paddle-pave-gold-hero_white.jpg', alt: 'Paddle Pav\u00e9 Gold — front view', label: 'Front View' },
      { src: '/images/paddle-pave-gold-hero_gradient.jpg', alt: 'Paddle Pav\u00e9 Gold — gradient', label: 'Gradient' },
      { src: '/images/paddle-pave-gold-on_model.jpg', alt: 'Paddle Pav\u00e9 Gold — on model', label: 'On Model' },
      { src: '/images/paddle-pave-gold-lifestyle_marble.jpg', alt: 'Paddle Pav\u00e9 Gold — lifestyle', label: 'Lifestyle' },
      { src: '/images/paddle-pave-gold-lifestyle_velvet.jpg', alt: 'Paddle Pav\u00e9 Gold — velvet', label: 'Velvet' },
      { src: '/images/paddle-pave-gold-sport_context.jpg', alt: 'Paddle Pav\u00e9 Gold — on court', label: 'On Court' },
      { src: '/images/paddle-pave-gold-detail_macro.jpg', alt: 'Paddle Pav\u00e9 Gold — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K Yellow Gold', weight: '5.8g', dimensions: '28mm \u00d7 16mm paddle', chain: '20" cable chain with lobster clasp' },
  },
  {
    id: 'paddle-pave-silver',
    productCode: 'GUP0006-VZ',
    name: 'Paddle Pav\u00e9 Silver',
    price: 1520,
    priceDisplay: '$1,520',
    collection: 'victory',
    category: 'pendant',
    description: 'The pav\u00e9 paddle pendant in white gold — a cooler, more contemporary take on our most iconic silhouette. Rhodium-plated for lasting brilliance, this piece pairs beautifully with silver-toned watches and white gold rings.',
    tagline: 'Cool. Collected. Iconic.',
    badges: ['Pav\u00e9 Diamond'],
    occasions: ['self-gift', 'gift', 'milestone', 'tournament-win'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/paddle-pave-silver-hero_white.jpg',
    complementaryIds: ['sparkle-studs-silver', 'sparkle-drops-silver'],
    gallery: [
      { src: '/images/paddle-pave-silver-hero_white.jpg', alt: 'Paddle Pav\u00e9 Silver — front view', label: 'Front View' },
      { src: '/images/paddle-pave-silver-hero_gradient.jpg', alt: 'Paddle Pav\u00e9 Silver — gradient', label: 'Gradient' },
      { src: '/images/paddle-pave-silver-on_model.jpg', alt: 'Paddle Pav\u00e9 Silver — on model', label: 'On Model' },
      { src: '/images/paddle-pave-silver-lifestyle_marble.jpg', alt: 'Paddle Pav\u00e9 Silver — lifestyle', label: 'Lifestyle' },
      { src: '/images/paddle-pave-silver-lifestyle_velvet.jpg', alt: 'Paddle Pav\u00e9 Silver — velvet', label: 'Velvet' },
      { src: '/images/paddle-pave-silver-sport_context.jpg', alt: 'Paddle Pav\u00e9 Silver — on court', label: 'On Court' },
      { src: '/images/paddle-pave-silver-detail_macro.jpg', alt: 'Paddle Pav\u00e9 Silver — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K White Gold', weight: '5.8g', dimensions: '28mm \u00d7 16mm paddle', chain: '20" cable chain with lobster clasp' },
  },
  {
    id: 'paddle-ball-gold',
    productCode: 'GUP0007',
    name: 'Paddle & Ball Gold',
    price: 1680,
    priceDisplay: '$1,680',
    collection: 'victory',
    category: 'pendant',
    description: 'Pav\u00e9 paddle meets pickleball — a gold paddle pendant with a miniature ball resting on its face. This dual-element design is our most narrative piece: the ball mid-rally, the paddle poised, the moment frozen in gold and diamond.',
    tagline: 'The moment, captured.',
    badges: ['Pav\u00e9 Diamond', 'Dual Element'],
    occasions: ['self-gift', 'gift', 'milestone', 'tournament-win', 'anniversary'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/paddle-ball-gold-hero_white.jpg',
    complementaryIds: ['paddle-pave-gold', 'sparkle-drops-gold'],
    gallery: [
      { src: '/images/paddle-ball-gold-hero_white.jpg', alt: 'Paddle & Ball Gold — front view', label: 'Front View' },
      { src: '/images/paddle-ball-gold-hero_gradient.jpg', alt: 'Paddle & Ball Gold — gradient', label: 'Gradient' },
      { src: '/images/paddle-ball-gold-on_model.jpg', alt: 'Paddle & Ball Gold — on model', label: 'On Model' },
      { src: '/images/paddle-ball-gold-lifestyle_marble.jpg', alt: 'Paddle & Ball Gold — lifestyle', label: 'Lifestyle' },
      { src: '/images/paddle-ball-gold-lifestyle_velvet.jpg', alt: 'Paddle & Ball Gold — velvet', label: 'Velvet' },
      { src: '/images/paddle-ball-gold-sport_context.jpg', alt: 'Paddle & Ball Gold — on court', label: 'On Court' },
      { src: '/images/paddle-ball-gold-detail_macro.jpg', alt: 'Paddle & Ball Gold — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K Yellow Gold', weight: '6.4g', dimensions: '30mm \u00d7 18mm paddle + 6mm ball', chain: '20" cable chain with lobster clasp' },
  },
  {
    id: 'paddle-ball-silver',
    productCode: 'GUP0007-VZ',
    name: 'Paddle & Ball Two-Tone',
    price: 1780,
    priceDisplay: '$1,780',
    collection: 'victory',
    category: 'pendant',
    description: 'Our most distinctive pendant — a white gold pav\u00e9 paddle crowned with a yellow gold pickleball. The two-tone contrast creates an arresting visual: warm gold ball on cool silver paddle, diamonds catching light from every direction.',
    tagline: 'Two metals. One moment.',
    badges: ['Pav\u00e9 Diamond', 'Two-Tone'],
    occasions: ['self-gift', 'gift', 'milestone', 'tournament-win', 'anniversary'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/paddle-ball-silver-hero_white.jpg',
    complementaryIds: ['paddle-pave-silver', 'sparkle-drops-silver'],
    gallery: [
      { src: '/images/paddle-ball-silver-hero_white.jpg', alt: 'Paddle & Ball Two-Tone — front view', label: 'Front View' },
      { src: '/images/paddle-ball-silver-hero_gradient.jpg', alt: 'Paddle & Ball Two-Tone — gradient', label: 'Gradient' },
      { src: '/images/paddle-ball-silver-on_model.jpg', alt: 'Paddle & Ball Two-Tone — on model', label: 'On Model' },
      { src: '/images/paddle-ball-silver-lifestyle_marble.jpg', alt: 'Paddle & Ball Two-Tone — lifestyle', label: 'Lifestyle' },
      { src: '/images/paddle-ball-silver-lifestyle_velvet.jpg', alt: 'Paddle & Ball Two-Tone — velvet', label: 'Velvet' },
      { src: '/images/paddle-ball-silver-sport_context.jpg', alt: 'Paddle & Ball Two-Tone — on court', label: 'On Court' },
      { src: '/images/paddle-ball-silver-detail_macro.jpg', alt: 'Paddle & Ball Two-Tone — detail', label: 'Detail' },
    ],
    specs: { metalType: '14K White Gold + Yellow Gold ball', weight: '6.4g', dimensions: '30mm \u00d7 18mm paddle + 6mm ball', chain: '20" cable chain with lobster clasp' },
  },

  // === SIGNATURE COLLECTION ($2,000–$7,000) ===
  {
    id: 'signature-ring',
    name: 'Signature Ring',
    price: 2200,
    priceDisplay: '$2,200',
    collection: 'signature',
    category: 'ring',
    description: 'Your initials, your motif, your metal — a ring as unique as your game.',
    badges: ['Engravable', 'Custom Motif'],
    occasions: ['anniversary', 'milestone', 'self-gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/signature-ring.jpg',
    complementaryIds: ['custom-initial-earrings', 'heritage-charm-bracelet'],
  },
  {
    id: 'heritage-charm-bracelet',
    name: 'Heritage Charm Bracelet',
    price: 3100,
    priceDisplay: '$3,100',
    collection: 'signature',
    category: 'bracelet',
    description: 'Collect your milestones. Each charm is hand-selected and set by our jewelers.',
    badges: ['Engravable'],
    occasions: ['anniversary', 'milestone', 'gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/heritage-charm-bracelet.jpg',
    complementaryIds: ['signature-ring', 'statement-court-pendant'],
  },
  {
    id: 'statement-court-pendant',
    name: 'Statement Court Pendant',
    price: 2800,
    priceDisplay: '$2,800',
    collection: 'signature',
    category: 'pendant',
    description: 'Bold proportions. Architectural lines. A pendant that starts conversations.',
    badges: ['Custom Motif'],
    occasions: ['self-gift', 'milestone', 'gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/statement-court-pendant.jpg',
    complementaryIds: ['milestone-cuff', 'custom-initial-earrings'],
  },
  {
    id: 'milestone-cuff',
    name: 'Milestone Cuff',
    price: 4500,
    priceDisplay: '$4,500',
    collection: 'signature',
    category: 'cuff',
    description: 'A solid gold cuff inscribed with the date of your defining moment on court.',
    badges: ['Engravable', 'Custom Motif'],
    occasions: ['anniversary', 'milestone', 'tournament-win'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/milestone-cuff.jpg',
    complementaryIds: ['signature-ring', 'champions-necklace'],
  },
  {
    id: 'custom-initial-earrings',
    name: 'Custom Initial Earrings',
    price: 2400,
    priceDisplay: '$2,400',
    collection: 'signature',
    category: 'earrings',
    description: 'Your letter, hand-cut in solid gold. Understated from the front, unmistakable in profile.',
    badges: ['Engravable'],
    occasions: ['gift', 'birthday', 'self-gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/custom-initial-earrings.jpg',
    complementaryIds: ['signature-ring', 'statement-court-pendant'],
  },
  {
    id: 'champions-necklace',
    name: "Champion's Necklace",
    price: 5200,
    priceDisplay: '$5,200',
    collection: 'signature',
    category: 'necklace',
    description: 'A layered chain with court-motif medallion. For those who carry their victories close.',
    badges: ['Engravable', 'Custom Motif'],
    occasions: ['tournament-win', 'milestone', 'anniversary'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/champions-necklace.jpg',
    complementaryIds: ['milestone-cuff', 'heritage-charm-bracelet'],
  },

  // === LEGACY COLLECTION ($7,000–$15,000) ===
  {
    id: 'dynasty-diamond-ring',
    name: 'Dynasty Diamond Ring',
    price: 8500,
    priceDisplay: '$8,500',
    collection: 'legacy',
    category: 'ring',
    description: 'A GIA-certified diamond set in a court-inspired mounting. Heirloom caliber.',
    badges: ['GIA Certified Diamond'],
    occasions: ['proposal', 'anniversary', 'milestone'],
    customizable: true,
    has3D: true,
    hasAR: true,
    image: '/images/dynasty-diamond-ring.jpg',
    complementaryIds: ['grand-slam-pendant', 'legacy-championship-bracelet'],
    diamondSpec: '1.0ct VS1 Round Brilliant',
  },
  {
    id: 'grand-slam-pendant',
    name: 'Grand Slam Pendant',
    price: 12000,
    priceDisplay: '$12,000',
    collection: 'legacy',
    category: 'pendant',
    description: 'A 1-carat diamond suspended in a paddle-motif setting. Our most iconic piece.',
    badges: ['1.0ct VS1 Round Brilliant'],
    occasions: ['anniversary', 'milestone', 'proposal'],
    customizable: true,
    has3D: true,
    hasAR: false,
    image: '/images/grand-slam-pendant.jpg',
    complementaryIds: ['dynasty-diamond-ring', 'legacy-championship-bracelet'],
    diamondSpec: '1.0ct VS1 Round Brilliant',
  },
  {
    id: 'legacy-championship-bracelet',
    name: 'Legacy Championship Bracelet',
    price: 9800,
    priceDisplay: '$9,800',
    collection: 'legacy',
    category: 'bracelet',
    description: 'Hand-set pavé diamonds along a solid gold band. A trophy for the wrist.',
    badges: ['Handset Pav\u00e9'],
    occasions: ['anniversary', 'milestone', 'tournament-win'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/legacy-championship-bracelet.jpg',
    complementaryIds: ['dynasty-diamond-ring', 'grand-slam-pendant'],
    diamondSpec: 'Pavé-set VS2 rounds',
  },
  {
    id: 'bespoke-commission',
    name: 'Bespoke Commission',
    price: 7000,
    priceDisplay: 'From $7,000',
    collection: 'legacy',
    category: 'commission',
    description: 'Your vision, realized by our master jewelers. From initial sketch to final polish.',
    badges: [],
    occasions: ['proposal', 'anniversary', 'milestone', 'gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/bespoke-commission.jpg',
    complementaryIds: [],
  },
];

export function getProductsByCollection(collection: Product['collection']): Product[] {
  return products.filter((p) => p.collection === collection);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getComplementaryProducts(productId: string): Product[] {
  const product = getProductById(productId);
  if (!product) return [];
  return product.complementaryIds
    .map((id) => getProductById(id))
    .filter((p): p is Product => p !== undefined);
}

export function getProductsByOccasion(occasion: string): Product[] {
  if (occasion === 'all') return products;
  return products.filter((p) => p.occasions.includes(occasion));
}
