import type { Product } from './types';

export const products: Product[] = [
  // === VICTORY COLLECTION ($500–$2,000) ===
  {
    id: 'court-pendant',
    name: 'Court Pendant',
    price: 520,
    priceDisplay: '$520',
    collection: 'victory',
    category: 'pendant',
    description: 'A refined court silhouette in polished gold — your daily reminder of every rally won.',
    badges: [],
    occasions: ['self-gift', 'birthday', 'tournament-win'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/court-pendant.jpg',
    complementaryIds: ['rally-bracelet', 'match-point-studs'],
  },
  {
    id: 'rally-bracelet',
    name: 'Rally Bracelet',
    price: 680,
    priceDisplay: '$680',
    collection: 'victory',
    category: 'bracelet',
    description: 'Stackable links that move with your game. Light enough to wear on court.',
    badges: [],
    occasions: ['self-gift', 'birthday', 'everyday'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/rally-bracelet.jpg',
    complementaryIds: ['court-pendant', 'match-point-studs'],
  },
  {
    id: 'match-point-studs',
    name: 'Match Point Studs',
    price: 450,
    priceDisplay: '$450',
    collection: 'victory',
    category: 'earrings',
    description: 'Subtle brilliance for every match day. Precision-cut ball motifs in solid gold.',
    badges: [],
    occasions: ['self-gift', 'birthday', 'everyday'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/match-point-studs.jpg',
    complementaryIds: ['court-pendant', 'ace-pendant'],
  },
  {
    id: 'ace-pendant',
    name: 'Ace Pendant',
    price: 750,
    priceDisplay: '$750',
    collection: 'victory',
    category: 'pendant',
    description: 'The iconic paddle silhouette, miniaturized into a wearable statement of identity.',
    badges: [],
    occasions: ['self-gift', 'gift', 'tournament-win'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/ace-pendant.jpg',
    complementaryIds: ['rally-bracelet', 'first-win-ring'],
  },
  {
    id: 'first-win-ring',
    name: 'First Win Ring',
    price: 890,
    priceDisplay: '$890',
    collection: 'victory',
    category: 'ring',
    description: 'Commemorate the moment the game became more than a game.',
    badges: [],
    occasions: ['tournament-win', 'milestone', 'self-gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/first-win-ring.jpg',
    complementaryIds: ['match-point-studs', 'ace-pendant'],
  },
  {
    id: 'drop-shot-charm',
    name: 'Drop Shot Charm',
    price: 560,
    priceDisplay: '$560',
    collection: 'victory',
    category: 'charm',
    description: 'A delicate net motif charm — subtle, layerable, unmistakably COURSET.',
    badges: [],
    occasions: ['self-gift', 'birthday', 'everyday'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/drop-shot-charm.jpg',
    complementaryIds: ['rally-bracelet', 'court-pendant'],
  },
  {
    id: 'court-royale-pendant',
    productCode: 'GUP0002',
    name: 'Court Royale',
    price: 980,
    priceDisplay: '$980',
    collection: 'victory',
    category: 'pendant',
    description: 'A miniature pickleball rendered in polished 14K gold — every hole precision-cut, every curve hand-finished. The Court Royale captures the soul of the game in a single, wearable sphere. Suspended from a delicate cable chain, it catches the light the way a rally catches your breath.',
    tagline: 'The game, distilled.',
    badges: [],
    occasions: ['self-gift', 'gift', 'birthday', 'tournament-win'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/court-royale-hero_white.jpg',
    complementaryIds: ['rally-drops-earrings', 'ace-studs-earrings', 'first-win-ring'],
    gallery: [
      { src: '/images/court-royale-hero_white.jpg', alt: 'Court Royale pendant — front view on white background', label: 'Front View' },
      { src: '/images/court-royale-hero_gradient.jpg', alt: 'Court Royale pendant — gradient background', label: 'Gradient' },
      { src: '/images/court-royale-lifestyle_marble.jpg', alt: 'Court Royale pendant — on marble with rose petal', label: 'Lifestyle' },
      { src: '/images/court-royale-lifestyle_velvet.jpg', alt: 'Court Royale pendant — dramatic shot on dark velvet', label: 'Velvet' },
      { src: '/images/court-royale-detail_macro.jpg', alt: 'Court Royale pendant — macro detail of gold surface', label: 'Detail' },
      { src: '/images/court-royale-banner_hero.jpg', alt: 'Court Royale pendant — banner view', label: 'Banner' },
    ],
    specs: {
      metalType: '14K Yellow Gold',
      weight: '3.2g',
      dimensions: '12mm sphere',
      chain: '18" cable chain with lobster clasp',
    },
  },
  {
    id: 'rally-drops-earrings',
    productCode: 'GUE0001',
    name: 'Rally Drops',
    price: 720,
    priceDisplay: '$720',
    collection: 'victory',
    category: 'earrings',
    description: 'Lever-back drop earrings shaped like miniature pickleballs, swinging with every step you take off the court. Each sphere is hand-perforated and polished to a mirror finish — catching light from every angle, turning heads at every gathering.',
    tagline: 'Movement meets brilliance.',
    badges: [],
    occasions: ['self-gift', 'gift', 'birthday', 'everyday'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/rally-drops-hero_white.jpg',
    complementaryIds: ['court-royale-pendant', 'ace-studs-earrings', 'rally-bracelet'],
    gallery: [
      { src: '/images/rally-drops-hero_white.jpg', alt: 'Rally Drops earrings — front view on white background', label: 'Front View' },
      { src: '/images/rally-drops-hero_gradient.jpg', alt: 'Rally Drops earrings — warm gradient background', label: 'Gradient' },
      { src: '/images/rally-drops-on_model.jpg', alt: 'Rally Drops earrings — worn on model', label: 'On Model' },
      { src: '/images/rally-drops-lifestyle_marble.jpg', alt: 'Rally Drops earrings — on marble surface', label: 'Lifestyle' },
      { src: '/images/rally-drops-lifestyle_velvet.jpg', alt: 'Rally Drops earrings — on dark velvet', label: 'Velvet' },
      { src: '/images/rally-drops-sport_context.jpg', alt: 'Rally Drops earrings — with pickleball equipment', label: 'On Court' },
      { src: '/images/rally-drops-detail_macro.jpg', alt: 'Rally Drops earrings — macro detail of gold surface', label: 'Detail' },
    ],
    specs: {
      metalType: '14K Yellow Gold',
      weight: '4.8g (pair)',
      dimensions: '12mm sphere, 28mm total drop',
      chain: 'Lever-back closure',
    },
  },
  {
    id: 'ace-studs-earrings',
    productCode: 'GUE0002',
    name: 'Ace Studs',
    price: 580,
    priceDisplay: '$580',
    collection: 'victory',
    category: 'earrings',
    description: 'Half-sphere pickleball studs that sit flush against the ear — bold enough to notice, subtle enough for every day. The push-back posts are engineered for comfort, so you can wear them from the morning match to the evening out.',
    tagline: 'Quiet confidence.',
    badges: [],
    occasions: ['self-gift', 'gift', 'birthday', 'everyday'],
    customizable: false,
    has3D: false,
    hasAR: false,
    image: '/images/ace-studs-hero_gradient.jpg',
    complementaryIds: ['court-royale-pendant', 'rally-drops-earrings', 'rally-bracelet'],
    gallery: [
      { src: '/images/ace-studs-hero_gradient.jpg', alt: 'Ace Studs earrings — gradient background showing front and side', label: 'Front View' },
      { src: '/images/ace-studs-on_model.jpg', alt: 'Ace Studs earrings — worn on model', label: 'On Model' },
      { src: '/images/ace-studs-lifestyle_marble.jpg', alt: 'Ace Studs earrings — on marble surface', label: 'Lifestyle' },
      { src: '/images/ace-studs-lifestyle_velvet.jpg', alt: 'Ace Studs earrings — on dark velvet', label: 'Velvet' },
      { src: '/images/ace-studs-sport_context.jpg', alt: 'Ace Studs earrings — with pickleball equipment', label: 'On Court' },
      { src: '/images/ace-studs-detail_macro.jpg', alt: 'Ace Studs earrings — macro detail of gold surface', label: 'Detail' },
      { src: '/images/ace-studs-banner_hero.jpg', alt: 'Ace Studs earrings — banner view', label: 'Banner' },
    ],
    specs: {
      metalType: '14K Yellow Gold',
      weight: '3.6g (pair)',
      dimensions: '10mm half-sphere',
      chain: 'Push-back butterfly closure',
    },
  },

  // === SIGNATURE COLLECTION ($2,000–$7,000) ===
  {
    id: 'signature-ring',
    name: 'Signature Ring',
    price: 2200,
    priceDisplay: '$2,200',
    collection: 'signature',
    category: 'ring',
    description: 'Your initials, your motif, your metal — a ring as unique as your game.',
    badges: ['Engravable', 'Custom Motif'],
    occasions: ['anniversary', 'milestone', 'self-gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/signature-ring.jpg',
    complementaryIds: ['custom-initial-earrings', 'heritage-charm-bracelet'],
  },
  {
    id: 'heritage-charm-bracelet',
    name: 'Heritage Charm Bracelet',
    price: 3100,
    priceDisplay: '$3,100',
    collection: 'signature',
    category: 'bracelet',
    description: 'Collect your milestones. Each charm is hand-selected and set by our jewelers.',
    badges: ['Engravable'],
    occasions: ['anniversary', 'milestone', 'gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/heritage-charm-bracelet.jpg',
    complementaryIds: ['signature-ring', 'statement-court-pendant'],
  },
  {
    id: 'statement-court-pendant',
    name: 'Statement Court Pendant',
    price: 2800,
    priceDisplay: '$2,800',
    collection: 'signature',
    category: 'pendant',
    description: 'Bold proportions. Architectural lines. A pendant that starts conversations.',
    badges: ['Custom Motif'],
    occasions: ['self-gift', 'milestone', 'gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/statement-court-pendant.jpg',
    complementaryIds: ['milestone-cuff', 'custom-initial-earrings'],
  },
  {
    id: 'milestone-cuff',
    name: 'Milestone Cuff',
    price: 4500,
    priceDisplay: '$4,500',
    collection: 'signature',
    category: 'cuff',
    description: 'A solid gold cuff inscribed with the date of your defining moment on court.',
    badges: ['Engravable', 'Custom Motif'],
    occasions: ['anniversary', 'milestone', 'tournament-win'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/milestone-cuff.jpg',
    complementaryIds: ['signature-ring', 'champions-necklace'],
  },
  {
    id: 'custom-initial-earrings',
    name: 'Custom Initial Earrings',
    price: 2400,
    priceDisplay: '$2,400',
    collection: 'signature',
    category: 'earrings',
    description: 'Your letter, hand-cut in solid gold. Understated from the front, unmistakable in profile.',
    badges: ['Engravable'],
    occasions: ['gift', 'birthday', 'self-gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/custom-initial-earrings.jpg',
    complementaryIds: ['signature-ring', 'statement-court-pendant'],
  },
  {
    id: 'champions-necklace',
    name: "Champion's Necklace",
    price: 5200,
    priceDisplay: '$5,200',
    collection: 'signature',
    category: 'necklace',
    description: 'A layered chain with court-motif medallion. For those who carry their victories close.',
    badges: ['Engravable', 'Custom Motif'],
    occasions: ['tournament-win', 'milestone', 'anniversary'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/champions-necklace.jpg',
    complementaryIds: ['milestone-cuff', 'heritage-charm-bracelet'],
  },

  // === LEGACY COLLECTION ($7,000–$15,000) ===
  {
    id: 'dynasty-diamond-ring',
    name: 'Dynasty Diamond Ring',
    price: 8500,
    priceDisplay: '$8,500',
    collection: 'legacy',
    category: 'ring',
    description: 'A GIA-certified diamond set in a court-inspired mounting. Heirloom caliber.',
    badges: ['GIA Certified Diamond'],
    occasions: ['proposal', 'anniversary', 'milestone'],
    customizable: true,
    has3D: true,
    hasAR: true,
    image: '/images/dynasty-diamond-ring.jpg',
    complementaryIds: ['grand-slam-pendant', 'legacy-championship-bracelet'],
    diamondSpec: '1.0ct VS1 Round Brilliant',
  },
  {
    id: 'grand-slam-pendant',
    name: 'Grand Slam Pendant',
    price: 12000,
    priceDisplay: '$12,000',
    collection: 'legacy',
    category: 'pendant',
    description: 'A 1-carat diamond suspended in a paddle-motif setting. Our most iconic piece.',
    badges: ['1.0ct VS1 Round Brilliant'],
    occasions: ['anniversary', 'milestone', 'proposal'],
    customizable: true,
    has3D: true,
    hasAR: false,
    image: '/images/grand-slam-pendant.jpg',
    complementaryIds: ['dynasty-diamond-ring', 'legacy-championship-bracelet'],
    diamondSpec: '1.0ct VS1 Round Brilliant',
  },
  {
    id: 'legacy-championship-bracelet',
    name: 'Legacy Championship Bracelet',
    price: 9800,
    priceDisplay: '$9,800',
    collection: 'legacy',
    category: 'bracelet',
    description: 'Hand-set pavé diamonds along a solid gold band. A trophy for the wrist.',
    badges: ['Handset Pav\u00e9'],
    occasions: ['anniversary', 'milestone', 'tournament-win'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/legacy-championship-bracelet.jpg',
    complementaryIds: ['dynasty-diamond-ring', 'grand-slam-pendant'],
    diamondSpec: 'Pavé-set VS2 rounds',
  },
  {
    id: 'bespoke-commission',
    name: 'Bespoke Commission',
    price: 7000,
    priceDisplay: 'From $7,000',
    collection: 'legacy',
    category: 'commission',
    description: 'Your vision, realized by our master jewelers. From initial sketch to final polish.',
    badges: [],
    occasions: ['proposal', 'anniversary', 'milestone', 'gift'],
    customizable: true,
    has3D: false,
    hasAR: false,
    image: '/images/bespoke-commission.jpg',
    complementaryIds: [],
  },
];

export function getProductsByCollection(collection: Product['collection']): Product[] {
  return products.filter((p) => p.collection === collection);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getComplementaryProducts(productId: string): Product[] {
  const product = getProductById(productId);
  if (!product) return [];
  return product.complementaryIds
    .map((id) => getProductById(id))
    .filter((p): p is Product => p !== undefined);
}

export function getProductsByOccasion(occasion: string): Product[] {
  if (occasion === 'all') return products;
  return products.filter((p) => p.occasions.includes(occasion));
}
